name: 'coverage'
on:
  pull_request:
    branches:
      - master
jobs:
  coverage:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Get Coverage
        uses: orgoro/coverage@v3
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Report Coverage
        uses: paambaati/codeclimate-action@v3.2.0