name: 'coverage'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  coverage:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Get Coverage
        uses: orgoro/coverage@v3
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Report Coverage
        uses: paambaati/codeclimate-action@v3.2.0