name: 'coverage'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  coverage:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Generate Report
        run: |
          pip install coverage
          coverage run -m unittests
      - name: Report Coverage
        uses: paambaati/codeclimate-action@v3.2.0